### ISSUE TITLE
Application not working / not listing the AP's in same network

### ISSUE THREAD

**Issue by sankethpb** [andersonhwang/cronus#1]
Hello @andersonhwang 

I tried to run this application via API and also the demo app.

Our AP is running is Local Network: 192.168.1.100
Store Name: 9812, AP/Station ID: 02

We launched the demo app / API (Cronus) in 192.168.1.230

The application started successfully, but doesn't list any AP's

Kindly advice on how to proceed, is there any settings to be made? Is there any option to specify the AP's IP address?

Does Cronus connect via ESL Management Software or directly to AP?

Request your support on the same.

Thanks,
Sanketh

**Comment by andersonhwang** [comment]
Hi Sanketh:

First, please check the AP version, this project currently only can work with ESL Gen 3 and AP Type 03.
And then, if you are not sure that your AP is configured correctly, you can press the reset button for seconds, and then use ConfigTool to re-configure again.
Last, the default store code is 0001 in  the demo, you can modify the source code, or re-configure the store code to 0001.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Sanketh P ***@***.***>
Sent: February 8, 2023 8:36 AM
To: ***@***.***>
Cc: Huang Hai ***@***.***>; ***@***.***>
Subject: [andersonhwang/cronus] Application not working / not listing the AP's in same network (Issue #1)


Hello @andersonhwang<https://github.com/andersonhwang>

I tried to run this application via API and also the demo app.

Our AP is running is Local Network: 192.168.1.100
Store Name: 9812, AP/Station ID: 02

We launched the demo app / API (Cronus) in 192.168.1.230

The application started successfully, but doesn't list any AP's

Kindly advice on how to proceed, is there any settings to be made? Is there any option to specify the AP's IP address?

Does Cronus connect via ESL Management Software or directly to AP?

Request your support on the same.

Thanks,
Sanketh

**Comment by sankethpb** [comment]
@andersonhwang Noted. Thank you.
When connected directly to PC and PC acting as server it works fine. I am able to communicate with the AP.
Probably some issue in internal network, we will check this.

**Comment by biskit** [comment]
did you manage to connect to it over the network?

**Comment by sankethpb** [comment]
Yes, we were able to connect. We had to create a separate VLAN for this and assign static IPs.
