### ISSUE TITLE
What is max. Battery Level?

### ISSUE THREAD

**Issue by sankethpb** [andersonhwang/cronus#2]
@andersonhwang : Request a clarification. What is the maximum battery level?
Here is says '3' for a brand new Tag. So id '3' the max or is there any spec. for this?

Thanks in advance.

**Comment by andersonhwang** [comment]
Hi, Sanketh:

The maximum battery level depends on the battery(one or two coin cell batteries, type CR2450), usually the value is 3.1~3.0v.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Sanketh P ***@***.***>
Sent: February 9, 2023 10:18 AM
To: ***@***.***>
Cc: Huang Hai ***@***.***>; ***@***.***>
Subject: [andersonhwang/cronus] What is max. Battery Level? (Issue #2)


@andersonhwang<https://github.com/andersonhwang> : Request a clarification. What is the maximum battery level?
Here is says '3' for a brand new Tag. So id '3' the max or is there any spec. for this?

Thanks in advance.
